<a href="https://colab.research.google.com/github/scbadkas19/NLP/blob/master/word_count.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
df=pd.read_json("http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Office_Products_5.json.gz",lines=True)
def word_count(str):
  count=dict()
  words=str.split()
  for word in words:
    if word in count:
      count[word]+=1
    else:
      count[word]=1
  return count
df['reviewText_wordcount']=df['reviewText'].apply(word_count)
df['summary_wordcount']=df['summary'].apply(word_count)
df

           reviewerID  ...                                  summary_wordcount
0      A32T2H8150OJLU  ...  {'A': 1, 'solid': 1, 'performer,': 1, 'and': 1...
1      A3MAFS04ZABRGO  ...  {'Price': 1, 'of': 1, 'GOLD': 1, 'is': 1, 'up,...
2      A1F1A0QQP2XVH5  ...  {'Good': 1, 'functionality,': 1, 'but': 1, 'no...
3       A49R5DBXXQDE5  ...  {'One': 1, 'of': 2, 'the': 1, 'last': 1, 'an':...
4      A2XRMQA6PJ5ZJ8  ...                  {'Still': 1, 'the': 1, 'best': 1}
...               ...  ...                                                ...
53253  A1ODOGXEYECQQ8  ...  {'Portable': 1, 'and': 1, 'very': 1, 'easy': 1...
53254  A2XX2A4OJCDNLZ  ...  {'Accuteck': 1, 'ShipPro': 1, 'Digital': 1, 'P...
53255  A3LGT6UZL99IW1  ...  {'Extremely': 1, 'accurate,': 1, 'foolproof': ...
53256  A1XJOSJN6FHFO0  ...   {'Fast,': 1, 'Easy': 1, 'and': 1, 'Accurate': 1}
53257   AAEVGE52KL0DJ  ...  {'Great': 1, 'Value': 1, 'on': 1, 'a': 1, 'Goo...

[53258 rows x 11 columns]